-- 코드를 입력하세요
SELECT PRODUCT_CODE, (PRICE*CNT) AS SALES
FROM PRODUCT P JOIN 
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS CNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) OS
ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;
