-- 코드를 입력하세요
SELECT
    TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT(A.USER_ID)) AS PUCHASED_USERS, -- 년, 월별 상품을 구매한 회원 수
    ROUND(COUNT(DISTINCT(A.USER_ID)) /
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PUCHASED_RATIO
    -- 안쪽 SELECT는 2021년에 가입한 전체 회원 수
FROM ONLINE_SALE A LEFT JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE TO_CHAR(JOINED, 'YYYY') = '2021'

GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')
ORDER BY YEAR, MONTH
;
