-- 코드를 입력하세요
SELECT FLAVOR
FROM(
    SELECT A.FLAVOR, SUM(A.TOTAL + B.TOTAL) AS TOTAL_SUM
    FROM
        (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL FROM FIRST_HALF GROUP BY FLAVOR) A,
        (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL FROM JULY GROUP BY FLAVOR) B
    WHERE A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    ORDER BY TOTAL_SUM DESC
    )
WHERE ROWNUM <= 3
;
