-- 코드를 입력하세요
SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD a, USED_GOODS_REPLY b
WHERE a.BOARD_ID = b.BOARD_ID AND YEAR(a.CREATED_DATE) = 2022 AND MONTH(a.CREATED_DATE) = 10
ORDER BY b.CREATED_DATE, a.TITLE;
